global_costmap:
  static_map : true
  update_frequency: 1.0
  publish_frequency: 0.5
  transform_tolerance : 0.5
  resolution : 0.025
  plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: laser_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: depth_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  # - {name: proxemiclayer, type: "social_navigation_layers::ProxemicLayer"}
  # - {name: passinglayer, type: "social_navigation_layers::PassingLayer"}