TrajectoryPlannerROS:
  acc_lim_x: 0.5
  acc_lim_y: 0
  acc_lim_theta: 3.2

  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  escape_vel: -0.1
  escape_reset_dist: 0.05

  holonomic_robot: false

  vx_samples: 3
  meter_scoring: true

  path_distance_bias: 0.75
  goal_distance_bias: 1.0
  occdist_scale: 0.01
  dwa: true

TebLocalPlannerROS:
  xy_goal_tolerance: 0.04
  yaw_goal_tolerance: 0.04

  acc_lim_x: 0.3
  acc_lim_y: 0
  acc_lim_theta: 3.2

  max_vel_x: 0.3
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  escape_vel: -0.1
  escape_reset_dist: 0.05
  include_dynamic_obstacles : true
  holonomic_robot: false

  vx_samples: 3
  meter_scoring: true

  path_distance_bias: 0.75
  goal_distance_bias: 1.0
  occdist_scale: 0.01
  dwa: true
  min_obstacle_dist: 0.3
  inflation_dist: 0.47
  dynamic_obstacle_inflation_dist: 0.47

  #reduce backwards motion
  weight_kinematics_forward_drive : 1000 #really high to discourage backwards movement
  allow_init_with_backwards_motion: false
  max_vel_x_backwards : 0.01