local_costmap:
  static_map : false
  update_frequency: 1.0
  publish_frequency: 1.0
  transform_tolerance : 0.5
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution : 0.025
  plugins:
  - {name: laser_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: depth_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  # - {name: proxemiclayer, type: "social_navigation_layers::ProxemicLayer"}
  # - {name: passinglayer, type: "social_navigation_layers::PassingLayer"}