controller_frequency: 10
controller_patience: 20

planner_frequency: 1
planner_patience: 15

max_planning_retries: 2
oscillation_timeout: 10
oscillation_distance: 0.2

base_local_planner: "teb_local_planner/TebLocalPlannerROS"
base_global_planner: "global_planner/GlobalPlanner"
#base_local_planner: "base_local_planner/TrajectoryPlannerROS"
#base_global_planner: "navfn/NavfnROS"